# Generated by Django 4.2.6 on 2023-12-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0002_alter_otvet_ball'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otvet',
            old_name='ball',
            new_name='otvet',
        ),
    ]
