# Generated by Django 4.2.6 on 2023-12-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0003_alter_modelprof_prof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voprosi',
            options={'ordering': ['-navik'], 'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
